services:
  production-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8080:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  keycloack:
    image: "quay.io/keycloak/keycloak:26.4"
    command:
      - "start"
      - "--import-realm"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KEYCLOACK_PASSWORD}"
      KC_HEALTH_ENABLED: "true"
      KC_FEATURES: "opentelemetry"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "keycloack"
    expose:
      - "8080"
      - "9000"
    volumes:
      - type: "volume"
        target: "/opt/keycloak/data"
        source: "keycloack-data"
        read_only: false
    networks:
      - "aspire"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "postgres-data"
        read_only: false
    networks:
      - "aspire"
  typesense:
    image: "typesense/typesense:29.0"
    environment:
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_ENABLE_CORS: "true"
      TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
    expose:
      - "8108"
    volumes:
      - type: "volume"
        target: "/data"
        source: "typesense-data"
        read_only: false
    networks:
      - "aspire"
  messaging:
    image: "docker.io/library/rabbitmq:4.2-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${MESSAGING_PASSWORD}"
    expose:
      - "5672"
      - "15672"
    volumes:
      - type: "volume"
        target: "/var/lib/rabbitmq"
        source: "rabbitmq-data"
        read_only: false
    networks:
      - "aspire"
  question-service:
    image: "${QUESTION_SERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${QUESTION_SERVICE_PORT}"
      KEYCLOACK_HTTP: "http://keycloack:8080"
      services__keycloack__http__0: "http://keycloack:8080"
      KEYCLOACK_MANAGEMENT: "http://keycloack:9000"
      services__keycloack__management__0: "http://keycloack:9000"
      ConnectionStrings__questionDb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=questionDb"
      QUESTIONDB_HOST: "postgres"
      QUESTIONDB_PORT: "5432"
      QUESTIONDB_USERNAME: "postgres"
      QUESTIONDB_PASSWORD: "${POSTGRES_PASSWORD}"
      QUESTIONDB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/questionDb"
      QUESTIONDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/questionDb"
      QUESTIONDB_DATABASENAME: "questionDb"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      MESSAGING_HOST: "messaging"
      MESSAGING_PORT: "5672"
      MESSAGING_USERNAME: "guest"
      MESSAGING_PASSWORD: "${MESSAGING_PASSWORD}"
      MESSAGING_URI: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "question-service"
    expose:
      - "${QUESTION_SERVICE_PORT}"
    depends_on:
      keycloack:
        condition: "service_started"
      postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  search-service:
    image: "${SEARCH_SERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SEARCH_SERVICE_PORT}"
      typesense-api-key: "${TYPESENSE_API_KEY}"
      TYPESENSE_TYPESENSE: "http://typesense:8108"
      services__typesense__typesense__0: "http://typesense:8108"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      MESSAGING_HOST: "messaging"
      MESSAGING_PORT: "5672"
      MESSAGING_USERNAME: "guest"
      MESSAGING_PASSWORD: "${MESSAGING_PASSWORD}"
      MESSAGING_URI: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "search-service"
    expose:
      - "${SEARCH_SERVICE_PORT}"
    depends_on:
      typesense:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  gateway:
    image: "mcr.microsoft.com/dotnet/nightly/yarp:2.3.0-preview.4"
    command:
      - "/app/yarp.dll"
    entrypoint:
      - "dotnet"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      QUESTION_SERVICE_HTTP: "http://question-service:${QUESTION_SERVICE_PORT}"
      REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/questions/{**catch-all}"
      REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_question-service"
      REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/tags/{**catch-all}"
      REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_question-service"
      REVERSEPROXY__ROUTES__route2__MATCH__PATH: "/search/{**catch-all}"
      REVERSEPROXY__ROUTES__route2__CLUSTERID: "cluster_search-service"
      REVERSEPROXY__CLUSTERS__cluster_question-service__DESTINATIONS__destination1__ADDRESS: "https+http://question-service"
      REVERSEPROXY__CLUSTERS__cluster_search-service__DESTINATIONS__destination1__ADDRESS: "https+http://search-service"
      services__question-service__http__0: "http://question-service:${QUESTION_SERVICE_PORT}"
      QUESTION_SERVICE_HTTPS: "https://question-service:${QUESTION_SERVICE_PORT}"
      SEARCH_SERVICE_HTTP: "http://search-service:${SEARCH_SERVICE_PORT}"
      services__search-service__http__0: "http://search-service:${SEARCH_SERVICE_PORT}"
      SEARCH_SERVICE_HTTPS: "https://search-service:${SEARCH_SERVICE_PORT}"
      ASPNETCORE_URLS: "http://*:8001"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway"
    ports:
      - "8001:8001"
    expose:
      - "5000"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  keycloack-data:
    driver: "local"
  postgres-data:
    driver: "local"
  typesense-data:
    driver: "local"
  rabbitmq-data:
    driver: "local"
